theme: jekyll-theme-minimal
page_title: Ruohan Wang -- Ph.D in Machine Learning
title: Ruohan Wang
tagline: Ph.D in Machine Learning
description: Research Scientist <br /> I2R, A*STAR
logo: me.jpg
cv_url: ruohan_cv.pdf
scholar_url: https://scholar.google.com/citations?user=2N3B7KgAAAAJ&hl=en
